# Generated by Django 5.1.6 on 2025-02-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_song_cover_image_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
