# Generated by Django 5.1.6 on 2025-03-18 08:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/YOUR_CLOUD_NAME/image/upload/v1700000000/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
